spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: truck-booking-platform
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/truck_platform}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true

server:
  port: 8082
  servlet:
    context-path: /api

app:
  jwt:
    secret: "your-secret-key-change-this-in-production-at-least-256-bits-long-with-minimum-32-chars"

logging:
  level:
    root: INFO
    com.truckplatform: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
